In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('train.csv')

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [5]:
df.rename(columns={'Name':'PassengerName'},inplace = True)

In [6]:
df.head()

,PassengerId,Survived,Pclass,PassengerName,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
df.columns =[x.upper() for x in df.columns]

In [8]:
df.head()

,PASSENGERID,SURVIVED,PCLASS,PASSENGERNAME,SEX,AGE,SIBSP,PARCH,TICKET,FARE,CABIN,EMBARKED
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [9]:
df.loc[2, 'EMBARKED' ] = 'C'

In [10]:
df.head()

,PASSENGERID,SURVIVED,PCLASS,PASSENGERNAME,SEX,AGE,SIBSP,PARCH,TICKET,FARE,CABIN,EMBARKED
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [11]:
df.loc[1,['CABIN', 'EMBARKED']] = [np.nan,'S']

In [12]:
df.head()

,PASSENGERID,SURVIVED,PCLASS,PASSENGERNAME,SEX,AGE,SIBSP,PARCH,TICKET,FARE,CABIN,EMBARKED
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [13]:
df.at[3,'EMBARKED'] = 'C'

In [14]:
df.head()

,PASSENGERID,SURVIVED,PCLASS,PASSENGERNAME,SEX,AGE,SIBSP,PARCH,TICKET,FARE,CABIN,EMBARKED
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,C
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [15]:
filt = (df['PASSENGERNAME'] == 'Futrelle, Mrs. Jacques Heath (Lily May Peel)')

In [16]:
df.loc[filt,'PASSENGERNAME'] = 'Futrelle, Mrs. Jacques Heath'

In [17]:
df.head()

,PASSENGERID,SURVIVED,PCLASS,PASSENGERNAME,SEX,AGE,SIBSP,PARCH,TICKET,FARE,CABIN,EMBARKED
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath",female,35.0,1,0,113803,53.1000,C123,C
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [18]:
df['PASSENGERNAME'] = df['PASSENGERNAME'].str.upper()

In [19]:
df.head()

,PASSENGERID,SURVIVED,PCLASS,PASSENGERNAME,SEX,AGE,SIBSP,PARCH,TICKET,FARE,CABIN,EMBARKED
0,1,0,3,"BRAUND, MR. OWEN HARRIS",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...",female,38.0,1,0,PC 17599,71.2833,NaN,S
2,3,1,3,"HEIKKINEN, MISS. LAINA",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,C
3,4,1,1,"FUTRELLE, MRS. JACQUES HEATH",female,35.0,1,0,113803,53.1000,C123,C
4,5,0,3,"ALLEN, MR. WILLIAM HENRY",male,35.0,0,0,373450,8.0500,NaN,S

In [20]:
df['PASSENGERNAME'] = df['PASSENGERNAME'].str.capitalize()

In [21]:
df.head()

,PASSENGERID,SURVIVED,PCLASS,PASSENGERNAME,SEX,AGE,SIBSP,PARCH,TICKET,FARE,CABIN,EMBARKED
0,1,0,3,"Braund, mr. owen harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, mrs. john bradley (florence briggs th...",female,38.0,1,0,PC 17599,71.2833,NaN,S
2,3,1,3,"Heikkinen, miss. laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,C
3,4,1,1,"Futrelle, mrs. jacques heath",female,35.0,1,0,113803,53.1000,C123,C
4,5,0,3,"Allen, mr. william henry",male,35.0,0,0,373450,8.0500,NaN,S

In [22]:
df['PASSENGERNAME'].apply(len)

0      23
1      51
2      22
3      28
4      24
       ..
886    21
887    28
888    40
889    21
890    19
Name: PASSENGERNAME, Length: 891, dtype: int64

In [23]:
df['PASSENGERNAME'] = df['PASSENGERNAME'].apply(lambda x: x.lower())

In [24]:
df.head()

,PASSENGERID,SURVIVED,PCLASS,PASSENGERNAME,SEX,AGE,SIBSP,PARCH,TICKET,FARE,CABIN,EMBARKED
0,1,0,3,"braund, mr. owen harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"cumings, mrs. john bradley (florence briggs th...",female,38.0,1,0,PC 17599,71.2833,NaN,S
2,3,1,3,"heikkinen, miss. laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,C
3,4,1,1,"futrelle, mrs. jacques heath",female,35.0,1,0,113803,53.1000,C123,C
4,5,0,3,"allen, mr. william henry",male,35.0,0,0,373450,8.0500,NaN,S

In [25]:
df.apply(len)

PASSENGERID      891
SURVIVED         891
PCLASS           891
PASSENGERNAME    891
SEX              891
AGE              891
SIBSP            891
PARCH            891
TICKET           891
FARE             891
CABIN            891
EMBARKED         891
dtype: int64

In [26]:
df.apply(len, axis='columns')

0      12
1      12
2      12
3      12
4      12
       ..
886    12
887    12
888    12
889    12
890    12
Length: 891, dtype: int64

In [27]:
df.loc[1,'PASSENGERNAME']

'cumings, mrs. john bradley (florence briggs thayer)'

In [28]:
df['PASSENGERNAME'].map({'cumings, mrs. john bradley (florence briggs thayer)': 'cumings, mrs. john bradley'})

0                             NaN
1      cumings, mrs. john bradley
2                             NaN
3                             NaN
4                             NaN
                  ...
886                           NaN
887                           NaN
888                           NaN
889                           NaN
890                           NaN
Name: PASSENGERNAME, Length: 891, dtype: object

In [29]:
df.head()

,PASSENGERID,SURVIVED,PCLASS,PASSENGERNAME,SEX,AGE,SIBSP,PARCH,TICKET,FARE,CABIN,EMBARKED
0,1,0,3,"braund, mr. owen harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"cumings, mrs. john bradley (florence briggs th...",female,38.0,1,0,PC 17599,71.2833,NaN,S
2,3,1,3,"heikkinen, miss. laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,C
3,4,1,1,"futrelle, mrs. jacques heath",female,35.0,1,0,113803,53.1000,C123,C
4,5,0,3,"allen, mr. william henry",male,35.0,0,0,373450,8.0500,NaN,S

In [30]:
df['PASSENGERNAME'].replace({'cumings, mrs. john bradley (florence briggs thayer)': 'cumings, mrs. john bradley'})

0                       braund, mr. owen harris
1                    cumings, mrs. john bradley
2                        heikkinen, miss. laina
3                  futrelle, mrs. jacques heath
4                      allen, mr. william henry
                         ...
886                       montvila, rev. juozas
887                graham, miss. margaret edith
888    johnston, miss. catherine helen "carrie"
889                       behr, mr. karl howell
890                         dooley, mr. patrick
Name: PASSENGERNAME, Length: 891, dtype: object

In [31]:
df.head()

,PASSENGERID,SURVIVED,PCLASS,PASSENGERNAME,SEX,AGE,SIBSP,PARCH,TICKET,FARE,CABIN,EMBARKED
0,1,0,3,"braund, mr. owen harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"cumings, mrs. john bradley (florence briggs th...",female,38.0,1,0,PC 17599,71.2833,NaN,S
2,3,1,3,"heikkinen, miss. laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,C
3,4,1,1,"futrelle, mrs. jacques heath",female,35.0,1,0,113803,53.1000,C123,C
4,5,0,3,"allen, mr. william henry",male,35.0,0,0,373450,8.0500,NaN,S

In [32]:
df['PASSENGERNAME'] = df['PASSENGERNAME'].replace({'cumings, mrs. john bradley (florence briggs thayer)': 'cumings, mrs. john bradley'})

In [33]:
df.head()

,PASSENGERID,SURVIVED,PCLASS,PASSENGERNAME,SEX,AGE,SIBSP,PARCH,TICKET,FARE,CABIN,EMBARKED
0,1,0,3,"braund, mr. owen harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"cumings, mrs. john bradley",female,38.0,1,0,PC 17599,71.2833,NaN,S
2,3,1,3,"heikkinen, miss. laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,C
3,4,1,1,"futrelle, mrs. jacques heath",female,35.0,1,0,113803,53.1000,C123,C
4,5,0,3,"allen, mr. william henry",male,35.0,0,0,373450,8.0500,NaN,S