In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('train.csv')

In [5]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df['Age'].median()

np.float64(28.0)

In [8]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [9]:
df['Age'].count()

np.int64(714)

In [10]:
df['Age'].value_counts()

Age
24.00    30
22.00    27
18.00    26
28.00    25
30.00    25
         ..
24.50     1
0.67      1
0.42      1
34.50     1
74.00     1
Name: count, Length: 88, dtype: int64

In [11]:
df['Age'].value_counts(normalize= True)

Age
24.00    0.042017
22.00    0.037815
18.00    0.036415
28.00    0.035014
30.00    0.035014
           ...
24.50    0.001401
0.67     0.001401
0.42     0.001401
34.50    0.001401
74.00    0.001401
Name: proportion, Length: 88, dtype: float64

In [13]:
df['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [14]:
df.groupby(['Age'])

In [15]:
age_grp = df.groupby(['Age'])

In [20]:
age_grp.get_group(24.00,)

C:\Users\Shalini Balla\AppData\Local\Temp\ipykernel_11932\599110485.py:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  age_grp.get_group(24.00,)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
89,90,0,3,"Celotti, Mr. Francesco",male,24.0,0,0,343275,8.0500,NaN,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C
127,128,1,3,"Madsen, Mr. Fridtjof Arne",male,24.0,0,0,C 17369,7.1417,NaN,S
139,140,0,1,"Giglio, Mr. Victor",male,24.0,0,0,PC 17593,79.2000,B86,C
142,143,1,3,"Hakkarainen, Mrs. Pekka Pietari (Elin Matilda ...",female,24.0,1,0,STON/O2. 3101279,15.8500,NaN,S
199,200,0,2,"Yrois, Miss. Henriette (""Mrs Harbeck"")",female,24.0,0,0,248747,13.0000,NaN,S
210,211,0,3,"Ali, Mr. Ahmed",male,24.0,0,0,SOTON/O.Q. 3101311,7.0500,NaN,S
234,235,0,2,"Leyson, Mr. Robert William Norman",male,24.0,0,0,C.A. 29566,10.5000,NaN,S
247,248,1,2,"Hamalainen, Mrs. William (Anna)",female,24.0,0,2,250649,14.5000,NaN,S
293,294,0,3,"Haas, Miss. Aloisia",female,24.0,0,0,349236,8.8500,NaN,S
294,295,0,3,"Mineff, Mr. Ivan",male,24.0,0,0,349233,7.8958,NaN,S
310,311,1,1,"Hays, Miss. Margaret Bechstein",female,24.0,0,0,11767,83.1583,C54,C
316,317,1,2,"Kantor, Mrs. Sinai (Miriam Sternin)",female,24.0,1,0,244367,26.0000,NaN,S
341,342,1,1,"Fortune, Miss. Alice Elizabeth",female,24.0,3,2,19950,263.0000,C23 C25 C27,S
345,346,1,2,"Brown, Miss. Amelia ""Mildred""",female,24.0,0,0,248733,13.0000,F33,S
369,370,1,1,"Aubart, Mme. Leontine Pauline",female,24.0,0,0,PC 17477,69.3000,B35,C
394,395,1,3,"Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengt...",female,24.0,0,2,PP 9549,16.7000,G6,S
437,438,1,2,"Richards, Mrs. Sidney (Emily Hocking)",female,24.0,2,3,29106,18.7500,NaN,S
499,500,0,3,"Svensson, Mr. Olof",male,24.0,0,0,350035,7.7958,NaN,S
514,515,0,3,"Coleff, Mr. Satio",male,24.0,0,0,349209,7.4958,NaN,S
565,566,0,3,"Davies, Mr. Alfred J",male,24.0,2,0,A/4 48871,24.1500,NaN,S
600,601,1,2,"Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...",female,24.0,2,1,243847,27.0000,NaN,S
615,616,1,2,"Herman, Miss. Alice",female,24.0,1,2,220845,65.0000,NaN,S
641,642,1,1,"Sagesser, Mlle. Emma",female,24.0,0,0,PC 17477,69.3000,B35,C
655,656,0,2,"Hickman, Mr. Leonard Mark",male,24.0,2,0,S.O.C. 14879,73.5000,NaN,S
710,711,1,1,"Mayne, Mlle. Berthe Antonine (""Mrs de Villiers"")",female,24.0,0,0,PC 17482,49.5042,C90,C
743,744,0,3,"McNamee, Mr. Neal",male,24.0,1,0,376566,16.1000,NaN,S
770,771,0,3,"Lievens, Mr. Rene Aime",male,24.0,0,0,345781,9.5000,NaN,S
858,859,1,3,"Baclini, Mrs. Solomon (Latifa Qurban)",female,24.0,0,3,2666,19.2583,NaN,C
864,865,0,2,"Gill, Mr. John William",male,24.0,0,0,233866,13.0000,NaN,S

In [21]:
age_grp.get_group(10.00,)

C:\Users\Shalini Balla\AppData\Local\Temp\ipykernel_11932\3760328657.py:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  age_grp.get_group(10.00,)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
419,420,0,3,"Van Impe, Miss. Catharina",female,10.0,0,2,345773,24.15,NaN,S
819,820,0,3,"Skoog, Master. Karl Thorsten",male,10.0,3,2,347088,27.90,NaN,S

In [23]:
age_grp['Sex'].value_counts().head(50)

Age    Sex
0.42   male       1
0.67   male       1
0.75   female     2
0.83   male       2
0.92   male       1
1.00   male       5
       female     2
2.00   female     6
       male       4
3.00   male       4
       female     2
4.00   female     5
       male       5
5.00   female     4
6.00   female     2
       male       1
7.00   male       2
       female     1
8.00   female     2
       male       2
9.00   female     4
       male       4
10.00  female     1
       male       1
11.00  male       3
       female     1
12.00  male       1
13.00  female     2
14.00  female     4
       male       2
14.50  female     1
15.00  female     4
       male       1
16.00  male      11
       female     6
17.00  male       7
       female     6
18.00  female    13
       male      13
19.00  male      18
       female     7
20.00  male      13
       female     2
20.50  male       1
21.00  male      17
       female     7
22.00  male      15
       female    12
23.00  male      10
       female     5
Name: count, dtype: int64

In [25]:
age_grp['Sex'].value_counts().loc[23.00]

Sex
male      10
female     5
Name: count, dtype: int64

In [28]:
age_grp['Survived'].median().head(50)

Age
0.42     1.0
0.67     1.0
0.75     1.0
0.83     1.0
0.92     1.0
1.00     1.0
2.00     0.0
3.00     1.0
4.00     1.0
5.00     1.0
6.00     1.0
7.00     0.0
8.00     0.5
9.00     0.0
10.00    0.0
11.00    0.0
12.00    1.0
13.00    1.0
14.00    0.5
14.50    0.0
15.00    1.0
16.00    0.0
17.00    0.0
18.00    0.0
19.00    0.0
20.00    0.0
20.50    0.0
21.00    0.0
22.00    0.0
23.00    0.0
23.50    0.0
24.00    0.5
24.50    0.0
25.00    0.0
26.00    0.0
27.00    1.0
28.00    0.0
28.50    0.0
29.00    0.0
30.00    0.0
30.50    0.0
31.00    0.0
32.00    0.5
32.50    0.5
33.00    0.0
34.00    0.0
34.50    0.0
35.00    1.0
36.00    0.5
36.50    0.0
Name: Survived, dtype: float64

In [29]:
age_grp['Survived'].agg(['median','mean'])

       median  mean
Age
0.42      1.0   1.0
0.67      1.0   1.0
0.75      1.0   1.0
0.83      1.0   1.0
0.92      1.0   1.0
...       ...   ...
70.00     0.0   0.0
70.50     0.0   0.0
71.00     0.0   0.0
74.00     0.0   0.0
80.00     1.0   1.0

[88 rows x 2 columns]

In [30]:
age_grp['Survived'].agg(['median','mean']).loc[50.00]

median    0.5
mean      0.5
Name: 50.0, dtype: float64

In [36]:
df['Survived'].value_counts(normalize = True)

Survived
0    0.616162
1    0.383838
Name: proportion, dtype: float64