In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('train.csv')

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df['Name with Ticket'] = df['Ticket']+' '+df['Name']

In [5]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Name with Ticket
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,"A/5 21171 Braund, Mr. Owen Harris"
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,"PC 17599 Cumings, Mrs. John Bradley (Florence ..."
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,"STON/O2. 3101282 Heikkinen, Miss. Laina"
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,"113803 Futrelle, Mrs. Jacques Heath (Lily May ..."
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,"373450 Allen, Mr. William Henry"

In [6]:
df.drop(columns=['Name','Ticket'])

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Name with Ticket
0,1,0,3,male,22.0,1,0,7.2500,NaN,S,"A/5 21171 Braund, Mr. Owen Harris"
1,2,1,1,female,38.0,1,0,71.2833,C85,C,"PC 17599 Cumings, Mrs. John Bradley (Florence ..."
2,3,1,3,female,26.0,0,0,7.9250,NaN,S,"STON/O2. 3101282 Heikkinen, Miss. Laina"
3,4,1,1,female,35.0,1,0,53.1000,C123,S,"113803 Futrelle, Mrs. Jacques Heath (Lily May ..."
4,5,0,3,male,35.0,0,0,8.0500,NaN,S,"373450 Allen, Mr. William Henry"
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,male,27.0,0,0,13.0000,NaN,S,"211536 Montvila, Rev. Juozas"
887,888,1,1,female,19.0,0,0,30.0000,B42,S,"112053 Graham, Miss. Margaret Edith"
888,889,0,3,female,NaN,1,2,23.4500,NaN,S,"W./C. 6607 Johnston, Miss. Catherine Helen ""Ca..."
889,890,1,1,male,26.0,0,0,30.0000,C148,C,"111369 Behr, Mr. Karl Howell"
890,891,0,3,male,32.0,0,0,7.7500,NaN,Q,"370376 Dooley, Mr. Patrick"

In [7]:
df['Name with Ticket'].str.split(' ')

0               [A/5, 21171, Braund,, Mr., Owen, Harris]
1      [PC, 17599, Cumings,, Mrs., John, Bradley, (Fl...
2          [STON/O2., 3101282, Heikkinen,, Miss., Laina]
3      [113803, Futrelle,, Mrs., Jacques, Heath, (Lil...
4                  [373450, Allen,, Mr., William, Henry]
                             ...
886                    [211536, Montvila,, Rev., Juozas]
887            [112053, Graham,, Miss., Margaret, Edith]
888    [W./C., 6607, Johnston,, Miss., Catherine, Hel...
889                   [111369, Behr,, Mr., Karl, Howell]
890                      [370376, Dooley,, Mr., Patrick]
Name: Name with Ticket, Length: 891, dtype: object

In [8]:
df['Name with Ticket'].str.split(' ',expand=True)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,A/5,21171,"Braund,",Mr.,Owen,Harris,None,None,None,None,None,None,None,None,None,None
1,PC,17599,"Cumings,",Mrs.,John,Bradley,(Florence,Briggs,Thayer),None,None,None,None,None,None,None
2,STON/O2.,3101282,"Heikkinen,",Miss.,Laina,None,None,None,None,None,None,None,None,None,None,None
3,113803,"Futrelle,",Mrs.,Jacques,Heath,(Lily,May,Peel),None,None,None,None,None,None,None,None
4,373450,"Allen,",Mr.,William,Henry,None,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,211536,"Montvila,",Rev.,Juozas,None,None,None,None,None,None,None,None,None,None,None,None
887,112053,"Graham,",Miss.,Margaret,Edith,None,None,None,None,None,None,None,None,None,None,None
888,W./C.,6607,"Johnston,",Miss.,Catherine,Helen,"""Carrie""",None,None,None,None,None,None,None,None,None
889,111369,"Behr,",Mr.,Karl,Howell,None,None,None,None,None,None,None,None,None,None,None
890,370376,"Dooley,",Mr.,Patrick,None,None,None,None,None,None,None,None,None,None,None,None

In [19]:
df2 = pd.read_csv('test.csv')

In [20]:
df2.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [22]:
pd.concat([df, df2])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Name with Ticket
0,1,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,"A/5 21171 Braund, Mr. Owen Harris"
1,2,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,"PC 17599 Cumings, Mrs. John Bradley (Florence ..."
2,3,1.0,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,"STON/O2. 3101282 Heikkinen, Miss. Laina"
3,4,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,"113803 Futrelle, Mrs. Jacques Heath (Lily May ..."
4,5,0.0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,"373450 Allen, Mr. William Henry"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,NaN,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,NaN
414,1306,NaN,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,NaN
415,1307,NaN,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,NaN
416,1308,NaN,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,NaN
417,1309,NaN,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,NaN

In [23]:
df.drop(index=2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Name with Ticket
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,"A/5 21171 Braund, Mr. Owen Harris"
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,"PC 17599 Cumings, Mrs. John Bradley (Florence ..."
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,"113803 Futrelle, Mrs. Jacques Heath (Lily May ..."
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,"373450 Allen, Mr. William Henry"
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,"330877 Moran, Mr. James"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,"211536 Montvila, Rev. Juozas"
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,"112053 Graham, Miss. Margaret Edith"
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,"W./C. 6607 Johnston, Miss. Catherine Helen ""Ca..."
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,"111369 Behr, Mr. Karl Howell"
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,"370376 Dooley, Mr. Patrick"

In [28]:
df.drop(index=df[df['Survived']==0].index)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Name with Ticket
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,"PC 17599 Cumings, Mrs. John Bradley (Florence ..."
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,"STON/O2. 3101282 Heikkinen, Miss. Laina"
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,"113803 Futrelle, Mrs. Jacques Heath (Lily May ..."
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,"347742 Johnson, Mrs. Oscar W (Elisabeth Vilhel..."
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,"237736 Nasser, Mrs. Nicholas (Adele Achem)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C,"2667 Najib, Miss. Adele Kiamie ""Jane"""
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,"11767 Potter, Mrs. Thomas Jr (Lily Alexenia Wi..."
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S,"230433 Shelley, Mrs. William (Imanita Parrish ..."
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,"112053 Graham, Miss. Margaret Edith"
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,"111369 Behr, Mr. Karl Howell"