In [13]:
import pandas as pd

In [14]:
df = pd.read_csv('train.csv')

In [15]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [16]:
df.set_index('PassengerId')

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [17]:
df.index

RangeIndex(start=0, stop=891, step=1)

In [18]:
df.set_index('PassengerId',inplace=True)

In [19]:
df.index

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       882, 883, 884, 885, 886, 887, 888, 889, 890, 891],
      dtype='int64', name='PassengerId', length=891)

In [20]:
df.loc[891]

Survived                      0
Pclass                        3
Name        Dooley, Mr. Patrick
Sex                        male
Age                        32.0
SibSp                         0
Parch                         0
Ticket                   370376
Fare                       7.75
Cabin                       NaN
Embarked                      Q
Name: 891, dtype: object

In [21]:
df.loc[891,'Name']

'Dooley, Mr. Patrick'

In [22]:
df.iloc[0]

Survived                          0
Pclass                            3
Name        Braund, Mr. Owen Harris
Sex                            male
Age                            22.0
SibSp                             1
Parch                             0
Ticket                    A/5 21171
Fare                           7.25
Cabin                           NaN
Embarked                          S
Name: 1, dtype: object

In [23]:
df.reset_index(inplace=True)

In [24]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [27]:
df.set_index('Name',inplace=True)

In [28]:
df.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S

In [29]:
df.sort_index()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Abbing, Mr. Anthony",846,0,3,male,42.0,0,0,C.A. 5547,7.5500,NaN,S
"Abbott, Mr. Rossmore Edward",747,0,3,male,16.0,1,1,C.A. 2673,20.2500,NaN,S
"Abbott, Mrs. Stanton (Rosa Hunt)",280,1,3,female,35.0,1,1,C.A. 2673,20.2500,NaN,S
"Abelson, Mr. Samuel",309,0,2,male,30.0,1,0,P/PP 3381,24.0000,NaN,C
"Abelson, Mrs. Samuel (Hannah Wizosky)",875,1,2,female,28.0,1,0,P/PP 3381,24.0000,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...
"de Mulder, Mr. Theodore",287,1,3,male,30.0,0,0,345774,9.5000,NaN,S
"de Pelsmaeker, Mr. Alfons",283,0,3,male,16.0,0,0,345778,9.5000,NaN,S
"del Carlo, Mr. Sebastiano",362,0,2,male,29.0,1,0,SC/PARIS 2167,27.7208,NaN,C
"van Billiard, Mr. Austin Blyler",154,0,3,male,40.5,0,2,A/5. 851,14.5000,NaN,S
"van Melkebeke, Mr. Philemon",869,0,3,male,NaN,0,0,345777,9.5000,NaN,S

In [30]:
df.sort_index(ascending=False)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"van Melkebeke, Mr. Philemon",869,0,3,male,NaN,0,0,345777,9.5000,NaN,S
"van Billiard, Mr. Austin Blyler",154,0,3,male,40.5,0,2,A/5. 851,14.5000,NaN,S
"del Carlo, Mr. Sebastiano",362,0,2,male,29.0,1,0,SC/PARIS 2167,27.7208,NaN,C
"de Pelsmaeker, Mr. Alfons",283,0,3,male,16.0,0,0,345778,9.5000,NaN,S
"de Mulder, Mr. Theodore",287,1,3,male,30.0,0,0,345774,9.5000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
"Abelson, Mrs. Samuel (Hannah Wizosky)",875,1,2,female,28.0,1,0,P/PP 3381,24.0000,NaN,C
"Abelson, Mr. Samuel",309,0,2,male,30.0,1,0,P/PP 3381,24.0000,NaN,C
"Abbott, Mrs. Stanton (Rosa Hunt)",280,1,3,female,35.0,1,1,C.A. 2673,20.2500,NaN,S
"Abbott, Mr. Rossmore Edward",747,0,3,male,16.0,1,1,C.A. 2673,20.2500,NaN,S
"Abbing, Mr. Anthony",846,0,3,male,42.0,0,0,C.A. 5547,7.5500,NaN,S