In [1]:
import pandas as pd

##### CSV

In [2]:
df = pd.read_csv('train.csv') # reading csv files , specify the file path

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
filt = (df['Age']==22.0)

In [5]:
age22 = df.loc[filt]

In [6]:
age22.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
60,61,0,3,"Sirayanian, Mr. Orsen",male,22.0,0,0,2669,7.2292,NaN,C
80,81,0,3,"Waelens, Mr. Achille",male,22.0,0,0,345767,9.0000,NaN,S
112,113,0,3,"Barton, Mr. David John",male,22.0,0,0,324669,8.0500,NaN,S
141,142,1,3,"Nysten, Miss. Anna Sofia",female,22.0,0,0,347081,7.7500,NaN,S

In [7]:
age22.to_csv('ageSpecific.csv') # export this new filtered data frame to a new csv file

##### TSV

In [8]:
age22.to_csv('ageSpecific.tsv', sep='\t') # export/writing this new filtered data frame to a new tsv file

In [9]:
df = pd.read_csv('ageSpecific.tsv',sep='\t') # reading/loading tsv files , specify the file path

##### EXCEL

In [12]:
%pip install openpyxl

Requirement already satisfied: openpyxl in C:\Users\Shalini Balla\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\Shalini Balla\AppData\Local\Programs\Python\Python314\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [13]:
age22.to_excel('ageSpecific.xlsx') # writing to a new excel file

In [14]:
test = pd.read_excel('ageSpecific.xlsx',index_col='PassengerId') # reading excel file

In [15]:
test.head()

,Unnamed: 0,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,,
1,0,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
61,60,0,3,"Sirayanian, Mr. Orsen",male,22,0,0,2669,7.2292,NaN,C
81,80,0,3,"Waelens, Mr. Achille",male,22,0,0,345767,9.0000,NaN,S
113,112,0,3,"Barton, Mr. David John",male,22,0,0,324669,8.0500,NaN,S
142,141,1,3,"Nysten, Miss. Anna Sofia",female,22,0,0,347081,7.7500,NaN,S

##### JSON

In [20]:
age22.to_json('ageSpecific.json') # writing to json file

In [24]:
test = pd.read_json('ageSpecific.json', orient = 'records', lines = True) #reading json files

In [25]:
test.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,None,S
1,61,0,3,"Sirayanian, Mr. Orsen",male,22,0,0,2669,7.2292,None,C
2,81,0,3,"Waelens, Mr. Achille",male,22,0,0,345767,9.0000,None,S
3,113,0,3,"Barton, Mr. David John",male,22,0,0,324669,8.0500,None,S
4,142,1,3,"Nysten, Miss. Anna Sofia",female,22,0,0,347081,7.7500,None,S

##### SQL

In [27]:
%pip install SQLAlchemy

Requirement already satisfied: SQLAlchemy in C:\Users\Shalini Balla\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.0.51)
Requirement already satisfied: greenlet>=1 in C:\Users\Shalini Balla\AppData\Local\Programs\Python\Python314\Lib\site-packages (from SQLAlchemy) (3.5.3)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\Shalini Balla\AppData\Local\Programs\Python\Python314\Lib\site-packages (from SQLAlchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [30]:
%pip install psycopg2_binary

Requirement already satisfied: psycopg2_binary in C:\Users\Shalini Balla\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.9.12)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [31]:
from sqlalchemy import create_engine

In [32]:
import psycopg2

In [ ]:
# install any sql database like mysql, postgreSQL, etc.

In [ ]:
engine = create_engine('postgresql://username: password@localhost:port number/'test table') 
# replace username, password with your credentials and port number too. create a new database in your preferred choice(postgre,mysql,etc) and specify it in place of test table here.

In [ ]:
age22.to_sql('test_table',engine) # writing to sql, new table will be created , we get error if table already exists

In [ ]:
age22.to_sql('test_table',engine, if_exists='replace') # new table will be created , we won't get any error if table already exists, original table will be replaced

In [ ]:
sql_df = pd.read_sql('test_table',engine,index_col='PassengerId') # reading sql

In [ ]:
sql_df.head()

In [ ]:
sql_df = pd.read_sql_query('Select * from test_table',engine,index_col='PassengerId') # to query on this dataframe

In [ ]:
sql_df.head()